//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpliFi.CCTC {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:nms:includeView", ConfigurationName="CCTC.includeViewMethodsSoap")]
    public interface includeViewMethodsSoap {
        
        // CODEGEN: Generating message contract since element name sessiontoken from namespace urn:nms:includeView is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="nms:includeView#createPesonalisationBlock", ReplyAction="*")]
        SimpliFi.CCTC.createPesonalisationBlockResponse createPesonalisationBlock(SimpliFi.CCTC.createPesonalisationBlockRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="nms:includeView#createPesonalisationBlock", ReplyAction="*")]
        System.Threading.Tasks.Task<SimpliFi.CCTC.createPesonalisationBlockResponse> createPesonalisationBlockAsync(SimpliFi.CCTC.createPesonalisationBlockRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class createPesonalisationBlockRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="createPesonalisationBlock", Namespace="urn:nms:includeView", Order=0)]
        public SimpliFi.CCTC.createPesonalisationBlockRequestBody Body;
        
        public createPesonalisationBlockRequest() {
        }
        
        public createPesonalisationBlockRequest(SimpliFi.CCTC.createPesonalisationBlockRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="urn:nms:includeView")]
    public partial class createPesonalisationBlockRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sessiontoken;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string namePersoBlock;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string labelPersoBlock;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public bool newPersoBlock;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string htmlContent;
        
        public createPesonalisationBlockRequestBody() {
        }
        
        public createPesonalisationBlockRequestBody(string sessiontoken, string namePersoBlock, string labelPersoBlock, bool newPersoBlock, string htmlContent) {
            this.sessiontoken = sessiontoken;
            this.namePersoBlock = namePersoBlock;
            this.labelPersoBlock = labelPersoBlock;
            this.newPersoBlock = newPersoBlock;
            this.htmlContent = htmlContent;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class createPesonalisationBlockResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="createPesonalisationBlockResponse", Namespace="urn:nms:includeView", Order=0)]
        public SimpliFi.CCTC.createPesonalisationBlockResponseBody Body;
        
        public createPesonalisationBlockResponse() {
        }
        
        public createPesonalisationBlockResponse(SimpliFi.CCTC.createPesonalisationBlockResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="urn:nms:includeView")]
    public partial class createPesonalisationBlockResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Result;
        
        public createPesonalisationBlockResponseBody() {
        }
        
        public createPesonalisationBlockResponseBody(string Result) {
            this.Result = Result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface includeViewMethodsSoapChannel : SimpliFi.CCTC.includeViewMethodsSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class includeViewMethodsSoapClient : System.ServiceModel.ClientBase<SimpliFi.CCTC.includeViewMethodsSoap>, SimpliFi.CCTC.includeViewMethodsSoap {
        
        public includeViewMethodsSoapClient() {
        }
        
        public includeViewMethodsSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public includeViewMethodsSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public includeViewMethodsSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public includeViewMethodsSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SimpliFi.CCTC.createPesonalisationBlockResponse SimpliFi.CCTC.includeViewMethodsSoap.createPesonalisationBlock(SimpliFi.CCTC.createPesonalisationBlockRequest request) {
            return base.Channel.createPesonalisationBlock(request);
        }
        
        public string createPesonalisationBlock(string sessiontoken, string namePersoBlock, string labelPersoBlock, bool newPersoBlock, string htmlContent) {
            SimpliFi.CCTC.createPesonalisationBlockRequest inValue = new SimpliFi.CCTC.createPesonalisationBlockRequest();
            inValue.Body = new SimpliFi.CCTC.createPesonalisationBlockRequestBody();
            inValue.Body.sessiontoken = sessiontoken;
            inValue.Body.namePersoBlock = namePersoBlock;
            inValue.Body.labelPersoBlock = labelPersoBlock;
            inValue.Body.newPersoBlock = newPersoBlock;
            inValue.Body.htmlContent = htmlContent;
            SimpliFi.CCTC.createPesonalisationBlockResponse retVal = ((SimpliFi.CCTC.includeViewMethodsSoap)(this)).createPesonalisationBlock(inValue);
            return retVal.Body.Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SimpliFi.CCTC.createPesonalisationBlockResponse> SimpliFi.CCTC.includeViewMethodsSoap.createPesonalisationBlockAsync(SimpliFi.CCTC.createPesonalisationBlockRequest request) {
            return base.Channel.createPesonalisationBlockAsync(request);
        }
        
        public System.Threading.Tasks.Task<SimpliFi.CCTC.createPesonalisationBlockResponse> createPesonalisationBlockAsync(string sessiontoken, string namePersoBlock, string labelPersoBlock, bool newPersoBlock, string htmlContent) {
            SimpliFi.CCTC.createPesonalisationBlockRequest inValue = new SimpliFi.CCTC.createPesonalisationBlockRequest();
            inValue.Body = new SimpliFi.CCTC.createPesonalisationBlockRequestBody();
            inValue.Body.sessiontoken = sessiontoken;
            inValue.Body.namePersoBlock = namePersoBlock;
            inValue.Body.labelPersoBlock = labelPersoBlock;
            inValue.Body.newPersoBlock = newPersoBlock;
            inValue.Body.htmlContent = htmlContent;
            return ((SimpliFi.CCTC.includeViewMethodsSoap)(this)).createPesonalisationBlockAsync(inValue);
        }
    }
}
